### ISSUE TITLE
Top 2016 To-Do List

### ISSUE THREAD

**Issue by lunik1** [brunel-physics/tqZ2015Code#17]
#### Synchronisation
- [x] Confirm that data and non-tZq MC and tZq results with SFs applied are consistent.
#### Systematics
- [x] Check generator level weight reweighting for Matrix Element and Parton Shower scale variations works as intended.
- [x] Update systematic variations for lepton triggers from our own studies.
- [x] Understand how to calculate systematic uncertainties for the trigger scale factors we have calculated.
- [x] Establish if any additional systematics are needed and implement them
#### Single lepton datasets
- [x] Use single lepton datasets to recover efficiency (low priority)
#### Mumu channel offset
- [x] Understand why ater the jet cuts are applied, data/MC yields don’t exceed 10% difference (+10% for bTagging, ~1-3% after jet and W mass cuts).
- [x] Check the trigger and lepton scale factors.
#### Control regions
- [x] Establish control regions
#### BDT
- [x] Update BDT for run 2
- [x] Establish which variables should be fed into the BDT
#### Combine tool
- [x] Create datacard
- [x] Figure out what commands need to be run
#### Background Estimation
- [x] Establish if trilepton approaches are still valid
- [x] Account for fake leptons
#### Scale factors
- [x] Establish if any scale factors need treating differently

**Comment by davidcarbonis** [comment]
Single lepton triggers are now being worked into the trunk. Closing this as everything else has been worked on.

**Comment by lunik1** [comment]
Great work!
